name: Checking PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  pr_check:
    name: PR Check
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association != 'CONTRIBUTOR' &&
      github.event.pull_request.author_association != 'MEMBER'
      )
    steps:
      - run: ${{ contains(fromJSON(env.keywords), github.event.pull_request.title) || contains(fromJSON(env.keywords), github.event.pull_request.description }}
        continue-on-error: true
        id: check
      - run: echo "Close PR"
        if: ${{ success() && steps.check.conclusion == 'failure' }}