name: PR check

on:
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  pr_check:
    name: Validate PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.author_association != 'CONTRIBUTOR' &&
      github.event.pull_request.author_association != 'MEMBER'
    steps:
      - run: ${{
          contains(fromJSON(secrets.RESTRICTED_KEYWORDS), github.event.pull_request.title) ||
          contains(fromJSON(secrets.RESTRICTED_KEYWORDS), github.event.pull_request.description) }}
        continue-on-error: true
        id: check
      - run: echo "Close PR"
        if: ${{ success() && steps.check.conclusion == 'failure' }}