name: PR check

on:
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  pr_check:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      if: ${{ 
      github.event.pull_request.author_association != 'CONTRIBUTOR' &&
      github.event.pull_request.author_association != 'MEMBER' &&
      (
        contains(fromJSON(secrets.RESTRICTED_KEYWORDS), github.event.pull_request.title) ||
        contains(fromJSON(secrets.RESTRICTED_KEYWORDS), github.event.pull_request.description)
      ) }}
    steps:
      - run: gh pr close
