name: PR check

on:
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  pr_check:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: load_keywords
        name: Load Keywords
        run: |
          keywords=$(jq -r '.[]' <<< "${{ secrets.RESTRICTED_KEYWORDS }}")
          echo "::set-output name=KEYWORDS::$keywords"
          # Silence the output
          echo "::silent::"

      - name: Check PR Content and Author Association
        run: |
          title=${{ github.event.pull_request.title }}
          description=${{ github.event.pull_request.body }}
          author_association=${{ github.event.pull_request.author_association }}
          for keyword in ${{ steps.load_keywords.outputs.KEYWORDS }}; do
            if [[ $title =~ $keyword || $description =~ $keyword ]]; then
              if [[ $author_association != 'CONTRIBUTOR' && $author_association != 'MEMBER' ]]; then
                gh pr close
                exit 1
              fi
            fi
          done
